### PR TITLE
Add regex to filter files to compile

### PR DESCRIPTION
**Pull request by liuyang1204**
Sometimes we want to watch a whole directory, but only compile some of the files.

### CODE REVIEW

**Comment by hawx** [comment]
You should be able to do this with `watch`, like:

```ruby
guard 'sass', output: 'styles' do
    watch(%r{files_[0-9].sass})
end
```

Reopen the pull request if this isn't the case; it is a long time since I've actually run this myself.

**Comment by liuyang1204** [comment]
Sorry, I didn't explain clearly.

My requirement was to watch the whole directory change, but only compile files matching the filter.

Your suggestion could not achieve this requirement since it simply ignores the changes of files which don't match the regex.

In my understanding, in this workflow, there are 2 sets of files:

1. Files to watch -- This can be controlled by Guard `watch` keyword
2. Files to compile -- This is currently all files in watch list except partial files

Partial files(starting with `_`) should be watched, but not compiled(Or compiled without generating a file).

Sometimes there are non-partial files (not starting with `_`) imported by other files.

Depending on the environment or the situation, I want to choose whether to generate compiled files for some of the non-partial files. That's the reason I sent this PR.

**Comment by e2** [comment]
@liuyang1204 - just some explanations that might be useful:

Guard watches whole directory tree always. The keyword `watch` is misleading, because it doesn't mean "watch the file/directory", it actually should be called "match".

Also Guard uses the global `:ignore` option to filter out changes you don't want. `watch` only has a pattern so that only files matching the pattern are handled.

`run_all` doesn't respond to changes, it's called manually by the user (or on startup).

That's why the `files` method exists: https://github.com/hawx/guard-sass/pull/56/files#diff-4d6e04a3b7277dd8ee3a15148db7cfa0L84

And since the `run_all` method calls `run_on_changes` anyway, you may want to filter in that method instead: https://github.com/hawx/guard-sass/pull/56/files#diff-4d6e04a3b7277dd8ee3a15148db7cfa0L147


But again, Guard's `watch` does matching anyway so @hawx 's reply is correct.

**Comment by liuyang1204** [comment]
@e2 I've tested this situation:

`b.scss` imports `a.scss`, and I have

```
guard 'sass', output: 'styles', all_on_start: true do
    watch(%r{b\.scss})
end
```

The facts are:

1. It only compiles `b.scss` on start
2. However I change `a.scss`, there is no trigger to recompile `b.scss`. There is actually no new log from Guard.

What I want is that it recompiles `b.scss`, whenever `a.scss` changes.

**Comment by e2** [comment]
@liuyang1204 - so basically a.scss is a partial, except it isn't named like one, right?

**Comment by e2** [comment]
@liuyang1204 - if a.scss is really a partial in a given project, you may want to just monkey-patch it in your `Guardfile` with:

```ruby
module Guard
  class Sass < Plugin
    def partial?(path)
      return true if path =~ /\/a.scss$/
      File.basename(path).start_with? '_'
    end
  end
end
```

And watch all *.scss files like it does by default.

**Comment by liuyang1204** [comment]
@e2 

> so basically a.scss is a partial, except it isn't named like one, right?

Well, It is partial or not depends on the situation. In some case, I would like to compile it and generate a `a.css`. In another case, I don't need to generate it.

E.x.

```
menu.scss
button.scss
nav.scss
all.scss # imports all other files
```

1. Sometimes I want to use separated css files for different components and `<link>` them if needed. In this case, I would like to generate css files for `menu, button, nav` but not `all.scss`.
2. Yet sometimes I want to use the whole css within one file, then I'll choose to build `all.scss` only.

**Comment by e2** [comment]
> Well, It is partial or not depends on the situation.

Yes, and that's why guard-sass should be able to know when it's compiled and when it's used as a partial.

I think ideally you should have 2 files: `_all.scss` and `all.scss` (which would import the partial`_all.scss`). One is a partial, one is a standalone file.

**Comment by hawx** [comment]
OK, I think I understand the problem here. Could you take a look at #57 and see if using `:resolve_all_dependencies` fixes your issue.

**Comment by liuyang1204** [comment]
@hawx 

Tried this branch `always_resolve_dependencies`, but I got error even when I add a single space to a file and save:

```
11:40:02 - ERROR - [Sass] Sass > Error: Invalid UTF-8 character "\x82"
> [#]         on line 57 of .sass-cache/4e83b96c1e81b5e1720b877353e1e9149e4af198/main.scssc
```

**Comment by e2** [comment]
@liuyang1204 - what encoding are you using?  

Sass has a `--default-encoding ENCODING` option, though guard-sass doesn't provide an option for setting it:

https://github.com/hawx/guard-sass/blob/master/lib/guard/sass.rb#L12

I think converting your source sass/scss files to UTF-8 will be the quickest thing to do.

**Comment by liuyang1204** [comment]
@e2 I'm always using UTF-8.

And I think it is not a problem of encoding, but maybe a bug introduced by #57

Since I didn't meet this error before switching to that branch.

**Comment by e2** [comment]
@liuyang1204 - unlikely. My guess is that you're using non-UTF-8 Windows-encoded "curly quotes".

Can you paste the line from that file?

**Comment by liuyang1204** [comment]
@e2 It's strange, but I can reproduce it.

I'm pretty sure it is not the problem of my file encoding or any character.

```
# Gemfile
gem 'guard-sass', git: 'https://github.com/hawx/guard-sass.git', branch: 'always-resolve-dependencies'

# Guardfile
guard 'sass', output: 'assets/css', all_on_start: true do
  watch(/main\.scss/)
end

# main.scss
div {
  height: 100px; 
}
```
`all_on_start` finished with no error.

Then I add a space in `main.scss` and save it.

The log reports:
```
11:45:48 - INFO - Sass [0.00s] ss/main.scss -> main.css

WARNING on line 1 of .sass-cache/92d7c505f5b35349be2f8f75e3c082c68b8c0ca4/main.scssc:
This selector doesn't have any properties and will not be rendered.
WARNING on line 2 of .sass-cache/92d7c505f5b35349be2f8f75e3c082c68b8c0ca4/main.scssc:
This selector doesn't have any properties and will not be rendered.
WARNING on line 3 of .sass-cache/92d7c505f5b35349be2f8f75e3c082c68b8c0ca4/main.scssc:
This selector doesn't have any properties and will not be rendered.
11:45:48 - ERROR - [Sass] Sass > Error: Invalid property: ":@children[o:Sass::Tree::RuleNode:".
> [#]         on line 4 of .sass-cache/92d7c505f5b35349be2f8f75e3c082c68b8c0ca4/main.scssc

```

**Comment by liuyang1204** [comment]
image

**Comment by e2** [comment]
@liuyang1204 - you're regexp rule is incorrect:

```ruby
 watch(/main\.scss/)
```

it should be:

 watch(/^main\.scss$/)

Because without the '$' it matches `main.scssc` too - and those are compiled files with a dumped Sass state. You're getting the error because Sass is trying to compile those files as if they were scss files.

**Comment by e2** [comment]
I think Guard would be easier if this feature was implemented: https://github.com/guard/guard/issues/649

**Comment by liuyang1204** [comment]
@e2 Thanks, that's my stupid mistake.

Just now I tested always-resolve-dependencies again, and found that it still couldn't solve this problem.

I only watched `main.scss` file, which imports other partials (not started with `_`)

Then I changed those partials, but `main.scss` was not recompiled.

**Comment by e2** [comment]
@liuyang1204 -

> @e2 Thanks, that's my stupid mistake.

If it's too easy to make a mistake, then it's the software's fault.

> I only watched main.scss file, which imports other partials (not started with _)

If you only watch `main.scss`, Guard won't tell Guard::Sass that your partial has changed when you edit it.

So you have to watch your partials too:

```ruby
watch(/main\.scss/)
watch(/^_.*.scss$/)
```

Guard doesn't open and read the files it's watching - so Guard won't know if e.g. `_mypartial.scss` is imported by your `main.scss`.

Here's how it works:

1. You edit a file, e.g. a partial
2. Guard sees that a file has changed, to it checks what you watch to see if it should respond.
3. Guard doesn't understand SASS, only Guard::Sass does. So Guard by itself doesn't know what "partial" even is.
4. If you're watching a partial, then Guard will tell Guard::Sass that the partial changed.
5. Now, Guard::Sass takes control and inspects what changed. If Guard::Sass detects a partial, it can decide what to rebuild.

So here's an updated `Guardfile` for you:

```ruby
guard 'sass', output: 'assets/css', all_on_start: true, always_resolve_dependencies: true, smart_partials: true do
  watch(/^main\.scss$/)
  watch(/^_.*\.scss$/)
end
```

Also, notice the extra options there. (`:smart_partials` and `:always_resolve_dependencies`).

**Comment by liuyang1204** [comment]
@e2 

Thanks!

I tested again, there was one positive change:

- If I change `partial.scss`, `main.scss` will be recompiled

But, it still recompiles `partial.scss`.

I want it not to recompile `partial.scss` in this situation.

**Comment by e2** [comment]
> I want it not to recompile partial.scss in this situation.

You want something that's very special and specific to your project. Neither Guard nor Guard::Sass has ANY way of knowing that "partial.scss" is a partial. 

By convention, the file should be named '_partial.scss'. If you don't want to follow this convention, you have to "tell" Guard::Sass that it's a partial.

The best way would be to monkey-patch, e.g.:

```ruby
module ::Guard
  class Sass < ::Guard::Plugin
    def partial?(path)
      return true if path =~ /\/partial.scss$/
      File.basename(path).start_with? '_'
    end
  end
end
```

This is the cleanest way - and it doesn't make sense to expect Guard::Sass to do this. You should rename your partials to start with '_'. If your project doesn't allow you to do that, I'd complain to the owner of the project.

**Comment by liuyang1204** [comment]
@e2 Got it, then I'll use monkey patch to solve my own problem.

And @hawx 

Thank you very much for kind help so far!

**Comment by hawx** [comment]
No problem, it does seem like you have a very unique situation that most people don't run across. 

Thanks @e2 for helping out.

**Comment by e2** [comment]
@hawx - I'm glad to help. I'm collecting all sorts of issues and use cases to make the next version of Guard better. I already see a few things worth improving based on this thread alone. Some are already planned.

There's also a ton of overlap between Guard plugins. The only "differences" are that one uses Haml, the other Coffeescript, another runs RSpec, etc. They all have some notion of "partials" and "dependencies", so there's no reason those should be implemented in separate codebases. (e.g. in RSpec, you can consider shared examples as "partials").

So if you have ideas or experiences, feel free to open issues in Guard.

**Pull request closed without merging**
